// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsw0nxH7ozWncfXplZF4bJdeoML93o10M',
    appId: '1:1079773130590:web:5820cd3bc5cdbab66769cf',
    messagingSenderId: '1079773130590',
    projectId: 'chatgptapp-e86e5',
    authDomain: 'chatgptapp-e86e5.firebaseapp.com',
    storageBucket: 'chatgptapp-e86e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrKgnQUFA9X34CnCMVHLfyiDjWNAJeIj4',
    appId: '1:1079773130590:android:84d4bd29b7cbd76c6769cf',
    messagingSenderId: '1079773130590',
    projectId: 'chatgptapp-e86e5',
    storageBucket: 'chatgptapp-e86e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXp7ZAc3IFvEhQ4DbWk2gnsuVZt1CYfgw',
    appId: '1:1079773130590:ios:df7732ba53baa0ef6769cf',
    messagingSenderId: '1079773130590',
    projectId: 'chatgptapp-e86e5',
    storageBucket: 'chatgptapp-e86e5.appspot.com',
    iosClientId: '1079773130590-45lpguofhs9agcbif26k9gohq305vvj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXp7ZAc3IFvEhQ4DbWk2gnsuVZt1CYfgw',
    appId: '1:1079773130590:ios:df7732ba53baa0ef6769cf',
    messagingSenderId: '1079773130590',
    projectId: 'chatgptapp-e86e5',
    storageBucket: 'chatgptapp-e86e5.appspot.com',
    iosClientId: '1079773130590-45lpguofhs9agcbif26k9gohq305vvj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgptApp',
  );
}
